### PR TITLE
Update bug_report

### LINKED ISSUE #5: AI integration
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by 0xitsHimanshu**
## Pull Request Tittle
Updated the Bug_report Template

## Description
Provide a brief summary of what this pull request does. Include any relevant details or background information.

## Type of Change

- [x] Bug fix
- [x] New feature
- [ ] Refactoring
- [ ] Documentation update
- [ ] Other (please specify)

## Checklist

- [ ] I have read the [CONTRIBUTING](LINK_TO_CONTRIBUTING.MD) document.
- [ ] I have followed the code style of this project
- [ ] I have added tests to cover my changes (if applicable)
- [ ] I have updated the documentation (if applicable)
- [ ] My changes generate no new warnings
- [ ] I have tested my changes locally
- [ ] I have checked the issue tracker to see if this change addresses an open issue (if applicable)

## Related Issue(s)
If this pull request fixes or addresses an issue, please reference it here (e.g., "Fixes #123" or "Closes #456").

Closes #5 

## Screenshots (if applicable)
If this PR includes UI changes, please include screenshots that show what has been modified.

## Additional Notes
Any additional information, comments, or concerns that may be relevant to this pull request.

### CODE REVIEW

**Review by Gtriggers — APPROVED** [review]
Approved!

**Review by aryansihag07 — CHANGES_REQUESTED** [review]
Add two to three lines more

**Review by aryansihag07 — APPROVED** [review]
Good work!

**Review by aryansihag07 — APPROVED** [review]
Approved!

**Review by Gtriggers — APPROVED** [review]

**Review by Gtriggers — APPROVED** [review]

**Review by aryansihag07 — APPROVED** [review]
Test review!

**Pull request merged**
